# Class notes for lecture one 

## Introduction, motivation, and administrivia (~30 min)

### Who am I (2 min)

### What to expect from this course (5 min)

Here are a list of things we will learn together during the course:

1. **Language**: what is the language that we use in drug discovery? How is the language of mathematics and informatics used?

2. **Process**: how do experts with diverse background communicate and collaborate to make drugs? What roles do mathematics and informatics play in this process?

3. **Model**: what types of models do we use in drug discovery? What are their advantages and limitations?

4. **Career**: How do you think of the sentence 'Biology is mathematician's next physics?' I was excited and humbled. Joel E. Cohen, an mathematical biologist, wrote eloquently in 2004 that 'Mathematics Is Biology's Next Microscope, Only Better; Biology Is Mathematics' Next Physics, Only Better'. Since drug discovery finally comes down to controlled perturbation of biological systems by biological and chemical means, I believe it is an attractive career path for mathematicians to understand the problems in drug discovery, and to use their knowledge and curiosity to help patients.

### Disclaimers (3 min)

* **Teaching is my personal engagement.** My opinions and views do not necessarily reflect those by F. Hoffmann-La Roche, my employer.

* **Please be aware of my biases and limitations.**
   * I am neither a mathematician nor a computer scientist by training. I am a computational biologist working in drug discovery. 
   * I see my task is to share with you the mathematical concepts and computational approaches used in drug discovery that I find beautiful and useful.  
   * I look forward to learning from you mathematics that I did not know.

### The format of the course (5 min)

* The course is touching a lot of disciplines, especially biology, chemistry, physics, besides mathematics and informatics. That has three implications:
    * The necessary working knowledge of other disciplines is introduced when it is needed.
    * We will not focus on rigorous proofs nor detailed deductions. Instead, we focus on key mathematical models that are important in drug discovery and computational concepts that are vital in translating data and models into knowledge that allow decision making.
    * I try to achieve a balance between the background and the mathematical and informatics part. Suggestions and ideas to improve the balance are always welcome.
* Each course starts at 12:15 on Fridays, and contains two 45-minute sessions.
* No exercise hours currently. Articles and book chapters for pre-reading and after-reading are distributed. Similar for videos. Each of us is encouraged to read them to get an overview of the topic to be covered, and to bring the questions to the course. 
* Later today we will introduce the workflow of drug discovery and the concept of multiscale modelling, and the lectures of the semester are organised around the workflow and the multiscale modelling model. We have nine course covering the entire drug-discovery processes. After that, we will have two courses where we invite several mathematicians working in drug discovery to share their personal experience in choosing drug discovery as a career, and their work. Last but not least, we will have a near-end-term presentation from each of us. More details about that later.
* We will use both board and presentation slides. Notes and slides will be available.
* The final note is given by participation (20%), presentation (30%), and an oral examination (50%). The oral examination will be about general concepts that we introduced, and about explaining mathematical concepts to a layman. Individual appointments have to be made for the oral examination.

## Part I

1. The linear view of drug discovery (~15 min).
1. The multiscale modelling view of drug discovery (~15 min).
1. Video by Susan Desmond-Hellmann (~15 min)

## Part II: student self-introduction (20 min)

* Name?
* Background?
* Which part of mathematics or informatics (or other background) are you mostly interested in?
* What do you want to take away from the course? Credit points, knowledge in drug discovery, applications of mathematics, or others?
