theme: jekyll-theme-cayman

assetbaseurl: https://accio.github.io/AMIDD

title: Applied Mathematics and Informatics in Drug Discovery (AMIDD)
email: jitao-david.zhang@unibas.ch
description: >- # this means to ignore newlines until "baseurl:"
  University of Basel/ Fall Semester 2021/ Fridays 12:15-14:00

plugins:
  - jekyll-feed

