serve:
	bundle exec jekyll serve

## see https://www.supertechcrew.com/jekyll-check-for-broken-links/ to learn about how to check links in jekyll
## in short, add ``gem 'rake'` and `gem 'html-proofer'` to the Gemfile, run `bundle install`
## and run the following command
htmlproofer:
	bundle exec jekyll build
	bundle exec htmlproofer ./_site
